// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnnqoejqgdmwadtzwuix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubnFvZWpxZ2Rtd2FkdHp3dWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDMzNjIsImV4cCI6MjA2NTUxOTM2Mn0.4ITA99C8PGmVjbcfGdJg9Ghnl9opP0XGEODjT-T6a0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);